import type { Product } from "./products"

export function sampleProducts(): Product[] {
  const now = new Date().toISOString()
  return [
    {
      slug: "premium-wireless-headphones",
      title: "Premium Wireless Headphones",
      description: "Noise-cancelling over-ear headphones with studio-grade sound in a minimal matte finish.",
      price: 299,
      currency: "USD",
      images: ["/premium-wireless-headphones.png"],
      category: "Audio",
      brand: "LUXE",
      rating: 4.7,
      inStock: true,
      variants: [{ name: "Color", value: "Black" }],
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "sleek-smartwatch",
      title: "Sleek Smartwatch",
      description: "Stainless steel smartwatch with AMOLED display and multi-day battery life.",
      price: 249,
      currency: "USD",
      images: ["/sleek-smartwatch.jpg"],
      category: "Wearables",
      brand: "LUXE",
      rating: 4.5,
      inStock: true,
      variants: [{ name: "Size", value: "42mm" }],
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "minimal-desk-lamp",
      title: "Minimal Desk Lamp",
      description: "Adjustable LED desk lamp with high CRI and anodized aluminum finish.",
      price: 129,
      currency: "USD",
      images: ["/minimal-desk-lamp.jpg"],
      category: "Home",
      brand: "LUXE",
      rating: 4.6,
      inStock: true,
      variants: [{ name: "Finish", value: "Black" }],
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "carbon-fiber-wallet",
      title: "Carbon Fiber Wallet",
      description: "RFID-blocking slim wallet crafted from premium carbon fiber.",
      price: 89,
      currency: "USD",
      images: ["/carbon-fiber-wallet.jpg"],
      category: "Accessories",
      brand: "LUXE",
      rating: 4.4,
      inStock: true,
      variants: [{ name: "Color", value: "Black" }],
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "studio-monitor-speakers",
      title: "Studio Monitor Speakers",
      description: "Compact nearfield monitors with balanced sound for music production and listening.",
      price: 199,
      currency: "USD",
      images: ["/smart-home-speaker.png"],
      category: "Audio",
      brand: "LUXE",
      rating: 4.3,
      inStock: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "wireless-earbuds",
      title: "Wireless Earbuds",
      description: "Low-latency Bluetooth earbuds with comfortable fit and pocketable case.",
      price: 149,
      currency: "USD",
      images: ["/premium-wireless-headphones-black-on-white.jpg"],
      category: "Audio",
      brand: "LUXE",
      rating: 4.2,
      inStock: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "linen-overshirt",
      title: "Linen Overshirt",
      description: "Breathable linen overshirt with relaxed fit and corozo buttons.",
      price: 79,
      currency: "USD",
      images: ["/organic-cotton-tee.png"],
      category: "Clothing",
      brand: "LUXE",
      rating: 4.1,
      inStock: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "minimal-sneakers",
      title: "Minimal Sneakers",
      description: "Full‑grain leather sneakers with cushioned insole and tonal stitching.",
      price: 159,
      currency: "USD",
      images: ["/designer-leather-handbag.png"],
      category: "Clothing",
      brand: "LUXE",
      rating: 4.4,
      inStock: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "ceramic-plant-pot",
      title: "Ceramic Plant Pot",
      description: "Matte ceramic planter with drainage and matching saucer.",
      price: 39,
      currency: "USD",
      images: ["/minimalist-ceramic-coffee-mug-set.png"],
      category: "Home",
      brand: "LUXE",
      rating: 4.2,
      inStock: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "aroma-diffuser",
      title: "Aroma Diffuser",
      description: "Ultrasonic diffuser with soft ambient light and auto‑shutoff.",
      price: 59,
      currency: "USD",
      images: ["/minimal-desk-lamp-studio-shot.jpg"],
      category: "Home",
      brand: "LUXE",
      rating: 4.0,
      inStock: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "vitamin-c-serum",
      title: "Vitamin C Serum",
      description: "Potent brightening serum with stabilized vitamin C and hyaluronic acid.",
      price: 45,
      currency: "USD",
      images: ["/diverse-products-still-life.png"],
      category: "Beauty",
      brand: "LUXE",
      rating: 4.3,
      inStock: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "silk-eye-mask",
      title: "Silk Eye Mask",
      description: "Mulberry silk eye mask for comfortable, uninterrupted sleep.",
      price: 29,
      currency: "USD",
      images: ["/diverse-user-avatars.png"],
      category: "Beauty",
      brand: "LUXE",
      rating: 4.6,
      inStock: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "usb-c-hub",
      title: "USB‑C Hub",
      description: "7‑in‑1 aluminum USB‑C hub with HDMI 4K and PD charging.",
      price: 79,
      currency: "USD",
      images: ["/sleek-smartwatch.jpg"],
      category: "Electronics",
      brand: "LUXE",
      rating: 4.2,
      inStock: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "mechanical-keyboard",
      title: "Mechanical Keyboard",
      description: "Low‑profile mechanical keyboard with hot‑swappable switches.",
      price: 129,
      currency: "USD",
      images: ["/modern-smartwatch-minimal-product-photo.jpg"],
      category: "Electronics",
      brand: "LUXE",
      rating: 4.5,
      inStock: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      slug: "leather-card-holder",
      title: "Leather Card Holder",
      description: "Slim card holder in vegetable‑tanned leather.",
      price: 49,
      currency: "USD",
      images: ["/carbon-fiber-wallet-macro.jpg"],
      category: "Accessories",
      brand: "LUXE",
      rating: 4.3,
      inStock: true,
      createdAt: now,
      updatedAt: now,
    },
  ]
}
